spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    properties.hibernate.format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
logging:
  level.org.hibernate.type.descriptor.sql: trace




